version: '3.9'

services:
  auth:
    build:
      context: .
      dockerfile: $PWD/apps/auth/dev.Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 7775:9229
    env_file:
      - $PWD/apps/auth/.env
