version: '3.9'

services:
  auth:
    build:
      context: .
      dockerfile: $PWD/apps/auth/dev.Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 7775:9229
    env_file:
      - $PWD/apps/auth/.env

  home-feed:
    build:
      context: .
      dockerfile: $PWD/apps/home-feed/dev.Dockerfile
    volumes:
      - .:/app
    ports:
      - 3001:3001
      - 7776:9229
    env_file:
      - $PWD/apps/home-feed/.env

  blog-writer:
    build:
      context: .
      dockerfile: $PWD/apps/blog-writer/dev.Dockerfile
    volumes:
      - .:/app
    ports:
      - 3002:3002
      - 7777:9229
    env_file:
      - $PWD/apps/blog-writer/.env

  follow:
    build:
      context: .
      dockerfile: $PWD/apps/follow/dev.Dockerfile
    volumes:
      - .:/app
    ports:
      - 3003:3003
      - 7778:9229
    env_file:
      - $PWD/apps/follow/.env

  database:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=kyle
      - POSTGRES_DB=nest-blog
    # tmpfs:
    #   - /var/lib/postgresql/data:rw
